import Head from 'next/head';
import { Inter } from '@next/font/google';
import { HomeModule } from '@/modules/imports';
import Header from '@/components/header';
import Footer from '@/components/footer';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Easyresume</title>
        <meta name="description" content="Generated by Easyresume" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <HomeModule />
      <Footer />
    </>
  );
}
